CREATE SCHEMA IF NOT EXISTS online_shop_schema;

SET search_path = "online_shop_schema";

CREATE TABLE online_shop_schema.sales
(
    sale_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sale_amount DOUBLE PRECISION                        NOT NULL,
    "fr"      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    "t"        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_sales PRIMARY KEY (sale_id)
);